### ISSUE TITLE
click to navigate not working

### ISSUE THREAD

**Issue by mo-han** [antoniotejada/Trilium-TocWidget#1]
trilium version: 0.50.3

anything did i miss or should i re-check?

**Comment by antoniotejada** [comment]
I've always had 0.50.3 and https://github.com/antoniotejada/Trilium-TocWidget/commit/2a5f36ddffe9f843955c2a3ddd1944eee0be153b works for me, both readonly and non-readonly text notes.

**Comment by mo-han** [comment]
the outline is displayed correctly, but cannot jump by clicking the header

**Comment by antoniotejada** [comment]
I understand, but it's working for me.

If you are familiar with the javascript console, you can set `#debugLevel=debug` in the tocwidget note attributes, enable the javascript console with `cltr+shift+i`, and paste the output.

This is what I get when I click on a topic:
```
TocWidget:  clicked
VM4220:174 TocWidget:  getActiveTabTextEditor
app_context.js:99 Unhandled command executeInActiveEditor, converting to event.
VM4220:92 TocWidget:  Finding headingIndex 5 in parent $root
VM4220:97 TocWidget:  Inspecting node: heading2, attrs: , path: 0
VM4220:97 TocWidget:  Inspecting node: heading3, attrs: , path: 1
VM4220:97 TocWidget:  Inspecting node: heading3, attrs: , path: 2
VM4220:97 TocWidget:  Inspecting node: heading4, attrs: , path: 3
VM4220:97 TocWidget:  Inspecting node: heading3, attrs: , path: 4
VM4220:97 TocWidget:  Inspecting node: heading2, attrs: , path: 5
VM4220:108 TocWidget:  Found heading node heading2
```

https://user-images.githubusercontent.com/6446344/166931416-dccf3f9b-6315-4831-93bb-47b3f7263829.mp4

**Comment by antoniotejada** [comment]
No repro and no steps to repro, screenshots video, console logs or anything, and no other reports of this basic functionality not working, closing.
